teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: bumperbot_controller/cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 3
        target: angular.z
        scale: 1.0